### ISSUE TITLE
MVP-4 : Web Interface

### ISSUE THREAD

**Issue by barbados-clemens** [barbados-clemens/shop-the-fridge#12]
Resources:
- Web

**Comment by barbados-clemens** [comment]
was thinking about statemangment. 
I am wanting to try out [xstate](https://xstate.js.org/docs/) not sure if anyone is super opposed.

**Comment by karnthis** [comment]
never heard of it, what does it bring to the table? not opposed, just curious.

**Comment by barbados-clemens** [comment]
https://xstate.js.org/viz/?gist=917b7d0c4992306057067c08166fdb7d

Here is an example of what a tape player would look like

basically provides a predictable and spec compliant way of handling states within your sepecific usage of the state machine.

**Comment by barbados-clemens** [comment]
closing as this is a generic issue that has no purpose now. Will open more specific issues when needed
