### ISSUE TITLE
Decide Priorities

### ISSUE THREAD

**Issue by barbados-clemens** [barbados-clemens/shop-the-fridge#16]

**Comment by barbados-clemens** [comment]
Priority should be to the backend api and setting up the project infrastructure after than we can work on making the frontend all pretty

**Comment by karnthis** [comment]
We need to identify the routes we are going to have for MVP. So far I have:
- CRUD for:
  - Ingredients (Items)
  - Shopping lists (Lists)
  - Recipes (Meals)
- Auth

**Comment by barbados-clemens** [comment]
I think this is a good start and what I'd considered min v1 spec. 

I think it would be okay to take on another feature for a v1, like sharing a recipe or something, but nothing too big in scope.

**Comment by spiray** [comment]
Do we have some ideas on schemas for the four tables?

**Comment by barbados-clemens** [comment]
check out #15 as that's where we are talking about what the data should look like @spiray

**Comment by spiray** [comment]
Cool thanks, Do we want to use this [Nest TypeORM tool](https://docs.nestjs.com/techniques/database) or do we want to go more raw and not use an ORM?

**Comment by barbados-clemens** [comment]
Just saw this. I think we should stick with TypeORM unless it just starts killing us in someway. But I doubt it. I hear good things from it. 

maybe @karnthis  can pipe in if he's used it yet with some api testing.

**Comment by karnthis** [comment]
I have TypeORM set up and working on local, but am having issues getting the tests to pass. Going to work on it more tonight.

**Comment by barbados-clemens** [comment]
Talked about in Discord Voice Chat. 
1. Get CRUD for all entities
1. Get Auth up and running
1. Basic UI/UX interactions (CRUD on Entities)
1. Battle Test to see where we are before continuing
