### ISSUE TITLE
Create Docker Postgres database for local dev

### ISSUE THREAD

**Issue by barbados-clemens** [barbados-clemens/shop-the-fridge#7]
Create a simple script to launch a local postgres db instance.

**Comment by Woddell** [comment]
are we wanting this to use docker-compose and have node & postgres as a stack? Or just a Dockerfile or script in readme for postgres?

**Comment by karnthis** [comment]
That is in the current PR @Woddell

**Comment by karnthis** [comment]
Resolved in PR #33
